# Generated by Django 4.2.6 on 2023-12-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newslet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslet',
            name='name',
        ),
    ]
