# Generated by Django 4.2.6 on 2023-12-03 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('bio', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(upload_to='Mahsulot/img')),
                ('status', models.CharField(max_length=2)),
            ],
        ),
    ]
